# SELF-PLAY
EPISODES = 25
MCTS_SIMS = 50
TAU_COUNTER = 25
MAX_GAME_LENGTH = 75
CPUCT = 5
EPSILON = 0.2
ALPHA = 0.8
MEMORY_CAP = 1000
MEMORY_MIN = 512

# RETRAINING
MINIBATCH_SIZE = 8
BATCH_SIZE = 256
EPOCHS = 2
REG_CONST = 0.0001
LEARNING_RATE = 0.1
MOMENTUM = 0.9
TRAINING_LOOPS = 50

# MODEL
NUM_FILTERS = 64
KERNEL_SIZE = (3, 3)
INPUT_SHAPE = (64, 4, 2)
NUM_HIDDEN = 6
HIDDEN_LAYERS = [{'filters':NUM_FILTERS, 'kernel_size': KERNEL_SIZE} for i in range(NUM_HIDDEN)]