EPISODES = 30
MCTS_SIMS = 25
TAU_COUNTER = 20
CPUCT = 1
EPSILON = 0.2
ALPHA = 0.8
MEMORY_CAP = 1000
BATCH_SIZE = 256
EPOCHS = 1
REG_CONST = 0.0001
LEARNING_RATE = 0.1
MOMENTUM = 0.9
TRAINING_LOOPS = 25

NUM_FILTERS = 75
KERNEL_SIZE = (4, 4)
NUM_HIDDEN = 8
HIDDEN_LAYERS = [{'filters':NUM_FILTERS, 'kernel_size': KERNEL_SIZE} for i in range(NUM_HIDDEN)]

EVAL_EPISODES = 20
SCORING_THRESHOLD = 1.3